# Site settings
title: ezQuake
description: "ezQuake - the #1 QuakeWorld client"
url: https://vikpe.org/ezquake.github.io/

# Build settings
markdown: kramdown
highlighter: rouge

# Handling/Reading
exclude:
  - .idea
  - Gemfile
  - Gemfile.lock
