# Site settings
title: ezQuake
description: "ezQuake - the #1 QuakeWorld client"
url: https://www.ezquake.com/

# Build settings
markdown: kramdown
highlighter: rouge

# Handling/Reading
exclude:
  - .idea
  - Gemfile
  - Gemfile.lock
