name: on ezQuake update

on:
  repository_dispatch:
    types: [ ezquake-updated ]

jobs:
  update_help_files:
    name: Update ezQuake help files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Delete existing help files
        run: rm _data/ezquake/*.json

      - name: Download help files from ezquake-source
        run: wget -i _data/ezquake/files_to_download.txt -P _data/ezquake

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit updated help files (if changed)
        with:
          commit_message: Update ezQuake help files.
          file_pattern: _data/ezquake/*.json
