name: ezQuake updated

on:
  repository_dispatch:
    types: [ ezquake-updated ]

jobs:
  update_help_files:
    name: Update ezQuake help files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Delete existing help files
        run: rm _data/ezquake/*.json

      - name: Download help files from ezquake-source
        run: wget -i _data/ezquake/files_to_download.txt -P _data/ezquake
        
      - run: ls -l
      - run: git status

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit updated help files.
          file_pattern: _data/ezquake/*.json
          # Optional commit user and author settings
          # commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          # commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
